name: CI/CD - Python Security Check with Bandit

on:
  push:
    branches:
      - main         # Запускать workflow на push в ветку main
  pull_request:
    branches:
      - main         # Запускать при создании pull request к ветке main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Укажите версию Python, которая нужна вашему приложению

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit security check
        run: |
          bandit -r .               # Запустить Bandit на всей директории проекта
